# Generated by Django 6.0.4 on 2026-04-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название проекта"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "short_description",
                    models.TextField(max_length=300, verbose_name="Короткое описание"),
                ),
                (
                    "full_description",
                    models.TextField(blank=True, verbose_name="Полное описание"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Категория"
                    ),
                ),
                (
                    "client",
                    models.CharField(blank=True, max_length=150, verbose_name="Клиент"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="projects/covers/", verbose_name="Обложка"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=True, verbose_name="Показывать в портфолио"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/examples/", verbose_name="Изображение"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подпись"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="landing.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение проекта",
                "verbose_name_plural": "Изображения проекта",
                "ordering": ["order", "id"],
            },
        ),
    ]
