# Generated by Django 6.0.4 on 2026-04-21 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(
                        default="обо мне",
                        max_length=100,
                        verbose_name="Надпись над заголовком",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(max_length=255, verbose_name="Главный заголовок"),
                ),
                ("hero_text", models.TextField(verbose_name="Текст под заголовком")),
                (
                    "values_title",
                    models.CharField(
                        default="Что мне близко",
                        max_length=255,
                        verbose_name="Заголовок блока ценностей",
                    ),
                ),
                (
                    "timeline_eyebrow",
                    models.CharField(
                        default="опыт",
                        max_length=100,
                        verbose_name="Надпись над опытом",
                    ),
                ),
                (
                    "timeline_title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок блока опыта"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Страница About",
                "verbose_name_plural": "Страница About",
            },
        ),
        migrations.CreateModel(
            name="AboutTimelineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=100, verbose_name="Период")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_items",
                        to="landing.aboutpage",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент таймлайна",
                "verbose_name_plural": "Элементы таймлайна",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AboutValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="landing.aboutpage",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ценность / принцип",
                "verbose_name_plural": "Ценности / принципы",
                "ordering": ["order", "id"],
            },
        ),
    ]
