# Generated by Django 6.0.4 on 2026-04-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_aboutpage_abouttimelineitem_aboutvalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Имя")),
                ("contact", models.CharField(max_length=255, verbose_name="Контакт")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Обработано"),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(
                        default="контакты",
                        max_length=100,
                        verbose_name="Надпись над заголовком",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(max_length=255, verbose_name="Главный заголовок"),
                ),
                ("hero_text", models.TextField(verbose_name="Текст под заголовком")),
                (
                    "card_kicker",
                    models.CharField(
                        default="контакты",
                        max_length=100,
                        verbose_name="Надпись в карточке",
                    ),
                ),
                (
                    "card_title",
                    models.CharField(
                        default="Давайте обсудим проект",
                        max_length=255,
                        verbose_name="Заголовок карточки",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "telegram_url",
                    models.URLField(blank=True, verbose_name="Ссылка на Telegram"),
                ),
                (
                    "telegram_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Текст Telegram"
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Ссылка на Instagram"),
                ),
                (
                    "instagram_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Текст Instagram"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Страница Contacts",
                "verbose_name_plural": "Страница Contacts",
            },
        ),
    ]
