# Generated by Django 6.0.4 on 2026-04-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0003_contactrequest_contactspage"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(max_length=150, verbose_name="Hero eyebrow"),
                ),
                (
                    "hero_title",
                    models.CharField(max_length=255, verbose_name="Hero title"),
                ),
                ("hero_text", models.TextField(verbose_name="Hero text")),
                (
                    "hero_primary_button_text",
                    models.CharField(
                        default="Смотреть работы",
                        max_length=100,
                        verbose_name="Текст первой кнопки",
                    ),
                ),
                (
                    "hero_primary_button_url",
                    models.CharField(
                        default="/portfolio/",
                        max_length=255,
                        verbose_name="URL первой кнопки",
                    ),
                ),
                (
                    "hero_secondary_button_text",
                    models.CharField(
                        default="Обсудить проект",
                        max_length=100,
                        verbose_name="Текст второй кнопки",
                    ),
                ),
                (
                    "hero_secondary_button_url",
                    models.CharField(
                        default="/contacts/",
                        max_length=255,
                        verbose_name="URL второй кнопки",
                    ),
                ),
                (
                    "hero_card_kicker",
                    models.CharField(
                        default="selected focus",
                        max_length=100,
                        verbose_name="Hero card kicker",
                    ),
                ),
                (
                    "hero_card_title",
                    models.CharField(
                        default="Brand mood",
                        max_length=150,
                        verbose_name="Hero card title",
                    ),
                ),
                ("hero_card_text", models.TextField(verbose_name="Hero card text")),
                (
                    "services_eyebrow",
                    models.CharField(
                        default="чем я занимаюсь",
                        max_length=100,
                        verbose_name="Eyebrow блока услуг",
                    ),
                ),
                (
                    "services_title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок блока услуг"
                    ),
                ),
                (
                    "approach_eyebrow",
                    models.CharField(
                        default="подход",
                        max_length=100,
                        verbose_name="Eyebrow блока подхода",
                    ),
                ),
                (
                    "approach_title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок блока подхода"
                    ),
                ),
                (
                    "cta_eyebrow",
                    models.CharField(
                        default="готовы начать",
                        max_length=100,
                        verbose_name="CTA eyebrow",
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(max_length=255, verbose_name="CTA title"),
                ),
                (
                    "cta_button_text",
                    models.CharField(
                        default="Связаться",
                        max_length=100,
                        verbose_name="CTA button text",
                    ),
                ),
                (
                    "cta_button_url",
                    models.CharField(
                        default="/contacts/",
                        max_length=255,
                        verbose_name="CTA button URL",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Главная страница",
                "verbose_name_plural": "Главная страница",
            },
        ),
        migrations.CreateModel(
            name="HomeApproachStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(default="01", max_length=10, verbose_name="Номер"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approach_steps",
                        to="landing.homepage",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг подхода",
                "verbose_name_plural": "Шаги подхода",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="landing.homepage",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга на главной",
                "verbose_name_plural": "Услуги на главной",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50, verbose_name="Значение")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="landing.homepage",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика",
                "verbose_name_plural": "Статистика",
                "ordering": ["order", "id"],
            },
        ),
    ]
