# Generated by Django 6.0.4 on 2026-04-21 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0004_homepage_homeapproachstep_homeservice_homestat"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kicker",
                    models.CharField(
                        default="01", max_length=20, verbose_name="Номер / kicker"
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ServicesPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(
                        default="услуги", max_length=100, verbose_name="Hero eyebrow"
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(max_length=255, verbose_name="Hero title"),
                ),
                ("hero_text", models.TextField(verbose_name="Hero text")),
                (
                    "cta_eyebrow",
                    models.CharField(
                        default="формат работы",
                        max_length=100,
                        verbose_name="CTA eyebrow",
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(max_length=255, verbose_name="CTA title"),
                ),
                (
                    "cta_button_text",
                    models.CharField(
                        default="Оставить заявку",
                        max_length=100,
                        verbose_name="CTA button text",
                    ),
                ),
                (
                    "cta_button_url",
                    models.CharField(
                        default="/contacts/",
                        max_length=255,
                        verbose_name="CTA button URL",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Страница Services",
                "verbose_name_plural": "Страница Services",
            },
        ),
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Пункт")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="landing.serviceitem",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт услуги",
                "verbose_name_plural": "Пункты услуги",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="landing.servicespage",
                verbose_name="Страница",
            ),
        ),
    ]
